name: Build and deploy preview

on:
  push:
    branches:
      - dev
      - dev-gh

env:
  NODE: 14

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - run: ruby --version
      - run: node --version

      - name: Install npm dependencies
        run: npm install

      - name: Build preview
        run: npm run preview

      - name: rsync preview
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: demo/
          remote_path: ${{ secrets.PREVIEW_PATH }}
          remote_host: ${{ secrets.PREVIEW_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.PREVIEW_USER }}
          remote_key: ${{ secrets.PREVIEW_KEY }}